# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/dim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/dim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dim/CLionProjects/Huffman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dim/CLionProjects/Huffman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/dim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/dim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/dim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/dim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/dim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/dim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/dim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/dim/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dim/CLionProjects/Huffman/CMakeFiles /home/dim/CLionProjects/Huffman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dim/CLionProjects/Huffman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named huffman_lib

# Build rule for target.
huffman_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 huffman_lib
.PHONY : huffman_lib

# fast build rule for target.
huffman_lib/fast:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/build
.PHONY : huffman_lib/fast

#=============================================================================
# Target rules for targets named huffman_cmake

# Build rule for target.
huffman_cmake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 huffman_cmake
.PHONY : huffman_cmake

# fast build rule for target.
huffman_cmake/fast:
	$(MAKE) -f CMakeFiles/huffman_cmake.dir/build.make CMakeFiles/huffman_cmake.dir/build
.PHONY : huffman_cmake/fast

bits_seq.o: bits_seq.cpp.o

.PHONY : bits_seq.o

# target to build an object file
bits_seq.cpp.o:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/bits_seq.cpp.o
.PHONY : bits_seq.cpp.o

bits_seq.i: bits_seq.cpp.i

.PHONY : bits_seq.i

# target to preprocess a source file
bits_seq.cpp.i:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/bits_seq.cpp.i
.PHONY : bits_seq.cpp.i

bits_seq.s: bits_seq.cpp.s

.PHONY : bits_seq.s

# target to generate assembly for a file
bits_seq.cpp.s:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/bits_seq.cpp.s
.PHONY : bits_seq.cpp.s

decoder.o: decoder.cpp.o

.PHONY : decoder.o

# target to build an object file
decoder.cpp.o:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/decoder.cpp.o
.PHONY : decoder.cpp.o

decoder.i: decoder.cpp.i

.PHONY : decoder.i

# target to preprocess a source file
decoder.cpp.i:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/decoder.cpp.i
.PHONY : decoder.cpp.i

decoder.s: decoder.cpp.s

.PHONY : decoder.s

# target to generate assembly for a file
decoder.cpp.s:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/decoder.cpp.s
.PHONY : decoder.cpp.s

encoder.o: encoder.cpp.o

.PHONY : encoder.o

# target to build an object file
encoder.cpp.o:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/encoder.cpp.o
.PHONY : encoder.cpp.o

encoder.i: encoder.cpp.i

.PHONY : encoder.i

# target to preprocess a source file
encoder.cpp.i:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/encoder.cpp.i
.PHONY : encoder.cpp.i

encoder.s: encoder.cpp.s

.PHONY : encoder.s

# target to generate assembly for a file
encoder.cpp.s:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/encoder.cpp.s
.PHONY : encoder.cpp.s

freq_tree.o: freq_tree.cpp.o

.PHONY : freq_tree.o

# target to build an object file
freq_tree.cpp.o:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/freq_tree.cpp.o
.PHONY : freq_tree.cpp.o

freq_tree.i: freq_tree.cpp.i

.PHONY : freq_tree.i

# target to preprocess a source file
freq_tree.cpp.i:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/freq_tree.cpp.i
.PHONY : freq_tree.cpp.i

freq_tree.s: freq_tree.cpp.s

.PHONY : freq_tree.s

# target to generate assembly for a file
freq_tree.cpp.s:
	$(MAKE) -f CMakeFiles/huffman_lib.dir/build.make CMakeFiles/huffman_lib.dir/freq_tree.cpp.s
.PHONY : freq_tree.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/huffman_cmake.dir/build.make CMakeFiles/huffman_cmake.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/huffman_cmake.dir/build.make CMakeFiles/huffman_cmake.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/huffman_cmake.dir/build.make CMakeFiles/huffman_cmake.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... huffman_lib"
	@echo "... huffman_cmake"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bits_seq.o"
	@echo "... bits_seq.i"
	@echo "... bits_seq.s"
	@echo "... decoder.o"
	@echo "... decoder.i"
	@echo "... decoder.s"
	@echo "... encoder.o"
	@echo "... encoder.i"
	@echo "... encoder.s"
	@echo "... freq_tree.o"
	@echo "... freq_tree.i"
	@echo "... freq_tree.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

